//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arma3ModOptionMover.Resource {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arma3ModOptionMover.Resource.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   There is no server list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsgNoServerList {
            get {
                return ResourceManager.GetString("ErrMsgNoServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Addons folder can not be found. ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsgNotFoundModAddonsPath {
            get {
                return ResourceManager.GetString("ErrMsgNotFoundModAddonsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {1} folder can not be found. ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsgNotFoundModOptionalsPath {
            get {
                return ResourceManager.GetString("ErrMsgNotFoundModOptionalsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MOD Path not found. ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsgNotFoundModPath {
            get {
                return ResourceManager.GetString("ErrMsgNotFoundModPath", resourceCulture);
            }
        }
    }
}
